function plot_effectivity_goal3(X1,fitting_vorschrift_array,fitting_vorschrift_array_sat, xu_lim,yu_lim,yl_lim, sat_point, g)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
f=g;
saturierung=[28 78 163 303]; %für Levels of Complexities
time_case={'early' , 'middle' , 'late' , 'constant'};
%  Auto-generated by MATLAB on 06-Jan-2016 10:17:27
%compl_size=strcat(num2str(g+1),'x',num2str(g+1));
figure_name=strcat('Effectivity_Goal_3_LMS_Size_', num2str(f+1),'x',num2str(f+1),'_Phase');
fig_title=strcat({'Effectivity: Goal 3 -'},{' '},num2str(f+1),{'x'},num2str(f+1),{' '},{'- LMS'});

% Create figure; size needs to be revised!
figure1 = figure('Name',figure_name);

% Create axes
axes1 = axes('Parent',figure1);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[yl_lim(g) yu_lim(g)]);
xlim([5 xu_lim(g)]);
box(axes1,'on');
hold(axes1,'on');
title(fig_title);
% Create ylabel

ylabel('Payoff');
% Create xlabel
xlabel('Time Limit [EIP]');
%y_daten=heuristics_result_matrix_s(:,10);
% Create multiple lines using matrix input to plot
% plot([x1; x2], [y1; y2])
plot1 = plot([X1(1:sat_point(1));X1(sat_point(1):end)],[fitting_vorschrift_array{1}(X1(1:sat_point(1))); fitting_vorschrift_array_sat{1}(X1(sat_point(1):end))],'Parent',axes1);
hold on;
plot2 = plot([X1(1:sat_point(2));X1(sat_point(2):end)],[fitting_vorschrift_array{2}(X1(1:sat_point(2))); fitting_vorschrift_array_sat{2}(X1(sat_point(2):end))],'Parent',axes1);
plot3 = plot([X1(1:sat_point(3));X1(sat_point(3):end)],[fitting_vorschrift_array{3}(X1(1:sat_point(3))); fitting_vorschrift_array_sat{3}(X1(sat_point(3):end))],'Parent',axes1);
plot4 = plot([X1(1:sat_point(4));X1(sat_point(4):end)],[fitting_vorschrift_array{4}(X1(1:sat_point(4))); fitting_vorschrift_array_sat{4}(X1(sat_point(4):end))],'Parent',axes1);
plot5 = plot([X1(1:sat_point(5));X1(sat_point(5):end)],[fitting_vorschrift_array{5}(X1(1:sat_point(5))); fitting_vorschrift_array_sat{5}(X1(sat_point(5):end))],'Parent',axes1);
plot6 = plot([X1(1:sat_point(6));X1(sat_point(6):end)],[fitting_vorschrift_array{6}(X1(1:sat_point(6))); fitting_vorschrift_array_sat{6}(X1(sat_point(6):end))],'Parent',axes1);
plot7 = plot([X1(1:sat_point(7));X1(sat_point(7):end)],[fitting_vorschrift_array{7}(X1(1:sat_point(7))); fitting_vorschrift_array_sat{7}(X1(sat_point(7):end))],'Parent',axes1);
plot8 = plot([X1(1:sat_point(8));X1(sat_point(8):end)],[fitting_vorschrift_array{8}(X1(1:sat_point(8))); fitting_vorschrift_array_sat{8}(X1(sat_point(8):end))],'Parent',axes1);
plot9 = plot([X1(1:sat_point(9));X1(sat_point(9):end)],[fitting_vorschrift_array{9}(X1(1:sat_point(9))); fitting_vorschrift_array_sat{9}(X1(sat_point(9):end))],'Parent',axes1);
plot10 = plot([X1(1:sat_point(10));X1(sat_point(10):end)],[fitting_vorschrift_array{10}(X1(1:sat_point(10))); fitting_vorschrift_array_sat{10}(X1(sat_point(10):end))],'Parent',axes1);

set(plot1,'DisplayName','Altruist', 'Color',[1,1,0]);%yellow
set(plot2,'DisplayName','Random', 'Color',[51/255,51/255,0]);%brown/olive
set(plot3,'DisplayName','Optimist', 'Color',[0,1,0]);%green
set(plot4,'DisplayName','Pessimist', 'Color',[1,0,0]);%red
set(plot5,'DisplayName','Naiive', 'Color',[51/255,1,1]);%türkis
set(plot6,'DisplayName','L2', 'Color',[1,51/255,0]);%orange
set(plot7,'DisplayName','D1', 'Color',[1,102/255,102/255]);%rosa
set(plot8,'DisplayName','D2', 'Color',[102/255,0,102/255]);%lila
set(plot9,'DisplayName','Equilibrium', 'Color',[0,0,1]);%blau
set(plot10,'DisplayName','pure Equilibrium match', 'Color','black'); %black

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','eastoutside','FontSize',9);

caxis([1,9]);

halbe_breite=((saturierung(f)-1)*3+5)*1/6;
for l=1:3

        x_line=[((saturierung(f)-1)*3+5)*l/3, ((saturierung(f)-1)*3+5)*l/3];
        y_line=[yl_lim(f),yu_lim(f)];

        y_l=line(x_line,y_line,'lineWidth', 1.5, 'lineStyle','--');
        y_l.Color=[0,0,0,0.5];
       labelpoints (x_line(1)-halbe_breite, y_line(1), time_case{l}, 'N', 0.2, 1, 'FontSize', 12, 'Color', [0.6 0.6 0.6]);
end
labelpoints ((x_line(1)+xu_lim(f))/2, y_line(1), time_case{l+1}, 'N', 0.2, 1, 'FontSize', 12, 'Color', [0.6 0.6 0.6]);

savefig(figure_name);
%saveas(figure1,figure_name, 'jpg');
saveas(figure1,figure_name, 'meta');
close(figure1);

